### ISSUE TITLE
Log to console option

### ISSUE THREAD

**Issue by mrwulf** [simulot/immich-go#799]
I'm running my import in a kubernetes job so I dump my google takeout into an NFS share and not worry about local storage space, my workstation going to sleep, etc.

Everything works great except there isn't any output to the console. Is there a way to pipe everything that goes to the log file to the console instead? It seem like that should be the default when `--no-ui` is passed to the command.

I used the Dockerfile from #306 and pushed to my own github repo for the image. And kick off a k8s job like so:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: immich-import
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - args:
        - upload
        - from-google-photos
        - --server=http://immich-server.household.svc.cluster.local:3001
        - --api-key=<redacted>
        - --include-untitled-albums=true
        - --manage-burst=Stack
        - --no-ui
        - --log-file=/takeouts/output.log.txt
        - /takeouts/takeout-*.zip
        image: ghcr.io/mrwulf/custom-images/immich-go:latest
        name: immich-import
        resources: {}
        volumeMounts:
        - mountPath: /takeouts
          name: takeouts
        workingDir: /takeouts
      volumes:
      - name: takeouts
        nfs:
          path: /mnt/user/backups/google-takeout
          server: nas.local

```
